CREATE TABLE tb_app_user(
    id VARCHAR(100) PRIMARY KEY UNIQUE NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    is_locked BOOLEAN DEFAULT FALSE,
    is_enabled BOOLEAN DEFAULT FALSE
);
